[package]
name = "collider_baker"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
bevy_mesh = "0.17"
shared = { path = "../../shared" }
serde = { workspace = true }
ron = "0.8"
bincode = "1.3"

